/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessSettings {
  'businessName' : string,
  'email' : string,
  'whatsappNumber' : string,
  'address' : string,
  'openingHours' : string,
  'phone' : string,
  'location' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'cakeType' : string,
  'customerPhone' : string,
  'flavor' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'size' : string,
  'deliveryDate' : string,
  'quantity' : bigint,
  'customerEmail' : string,
  'specialNotes' : string,
}
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, number, string, string, boolean],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getSettings' : ActorMethod<[], BusinessSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, string, string, bigint, string, string],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], boolean>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, string, string, boolean],
    boolean
  >,
  'updateSettings' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
